# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-12 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textcourse', '0002_auto_20180812_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpttarticle',
            name='order',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='order'),
        ),
    ]
