# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-12 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textcourse', '0003_mpttarticle_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpttarticle',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='textcourse.Course'),
            preserve_default=False,
        ),
    ]
