# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textcourse', '0004_auto_20180812_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpttarticle',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
