# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-05 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textcourse', '0006_course_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
