# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-07 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('url', models.URLField(max_length=100, verbose_name='url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/serial/', verbose_name='image')),
                ('order', models.IntegerField(blank=True, default=-1, null=True, verbose_name='order')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-updated'],
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entry',
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('abstract', models.CharField(blank=True, max_length=500, null=True, verbose_name='abstract')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/serial/', verbose_name='image')),
                ('order', models.IntegerField(blank=True, default=-1, null=True, verbose_name='order')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-updated'],
                'verbose_name': 'Serial',
                'verbose_name_plural': 'Serial',
            },
        ),
    ]
