# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-07 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='serial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serials.Serial', verbose_name='serial'),
            preserve_default=False,
        ),
    ]
