# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
        ('serials', '0002_entry_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='serials_serialpluginmodel', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='serial',
            name='abstract',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='serialpluginmodel',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serials.Serial'),
        ),
    ]
