# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-05 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0005_auto_20181006_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
    ]
